### ISSUE TITLE
Polling a done future

### ISSUE THREAD

**Issue by mbuesch** [jamesmunns/cassette#4]
Hi,

I'm wondering what the reasons behind this TODO are:
https://github.com/jamesmunns/cassette/blob/main/src/lib.rs#L341

I currently have a use case where I want to poll a future that becomes read every now and then.
That is a problem with cassette, because
* Cassette::new consumes the future and there's currently no way to retrieve it back (into_inner).
* poll_on refuses to work if it was ready once.

My current workaround is that I have a wrapper future around my actual future and I re-create the Cassette with the wrapper every time it becomes ready.
That works, but is less than optimal, though.
I do not want to re-create the actual future that I'm polling, because that has side effects.

Therefore, what are the options for a Cassette change?
How could this todo!() be removed?
If not, would it be acceptable, if an unwrap (consuming into_inner) would be added to retrieve the future, so that I can re-create the Cassette with the same future?

Thanks in advance.

**Comment by Finomnis** [comment]
What's your usecase? A future shouldn't become ready every now and then, it should become ready exactly once; reason is that it has to produce a value at some point, and it shouldn't have to produce the value repeatedly.

Your usecase sounds more as if it should utilize something like [tokio's streams](https://tokio.rs/tokio/tutorial/streams).

**Comment by Finomnis** [comment]
It even is a direct violation of the [poll()](https://doc.rust-lang.org/std/future/trait.Future.html#tymethod.poll) function:

> Once a future has finished, clients should not poll it again.

**Comment by mbuesch** [comment]
The question was: Why is it a TODO?
If this is so clearly defined, then this should be a panic instead.

**Comment by Finomnis** [comment]
> The question was: Why is it a TODO? If this is so clearly defined, then this should be a panic instead.

I agree.

**Comment by Finomnis** [comment]
Fixed through https://github.com/jamesmunns/cassette/commit/2e8de88183cc2be9bfe533e0dd0bad4e6dd0c970.
