### ISSUE TITLE
Usage at first not really clear.

### ISSUE THREAD

**Issue by Slamy** [jamesmunns/cassette#6]
I wasn't really sure whether i should write this issue or not. It might be possible that I'm the problem here. But still you have written this library and maybe you can help me and the next unlucky person.
First of all, thank you for this library. It is a nice idea for embedded rust and I wanted to use it for a small private project. I've learned using your demo application and also the readme you have provided.
Sadly there is a huge disconnect between real usage and the demo. Your work on sprocket-boot actually made it click for me. But before that I've spent 3 days of pure pain and even so it made click, I don't understand why and how.
Please let me elaborate:

This code is based on the demo. It doesn't do anything useful. The thing is that it does not compile and I don't understand why that is.
```rs
struct SlowPrinter {
    list: VecDeque<i32>,
}

impl Future for SlowPrinter {
    type Output = ();

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        if let Some(x) = self.list.pop_back() {
            println!("{}", x);
            Poll::Pending
        } else {
            Poll::Ready(())
        }
    }
}
async fn print_some(mut printer: SlowPrinter) {
    printer.await;
    printer.await; // !!! <-- This causes error !!!
}
```
VecDeque is something which doesn't implement the Copy trait. I'm fully aware why that is but I don't understand why await does require it. What is wrong with this example. Please teach me.
```
error[E0382]: use of moved value: `printer`
   --> tool/src/main.rs:160:5
    |
158 | async fn print_some(mut printer: SlowPrinter) {
    |                     ----------- move occurs because `printer` has type `SlowPrinter`, which does not implement the `Copy` trait
159 |     printer.await;
    |            ------ `printer` moved due to this method call
160 |     printer.await; // !!! Uncommenting causes error !!!
    |     ^^^^^^^ value used here after move
    |
note: this function takes ownership of the receiver `self`, which moves `printer`
   --> /home/andre/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/into_future.rs:128:20
    |
128 |     fn into_future(self) -> Self::IntoFuture;
    |                    ^^^^
```
    
Then again this here does compile. My problem here is that poll_fn was not mentioned in the demo, so I missed it.
Also I'm not able grasp what is different. I do realize that this is by far no issue of cassette. It is an issue with async. But I'm not even able to proper phrase the problem to get tutorials or manuals about this. Every async book or blog I've found so far doesn't provide infos about ownership in async.

```rs
struct SlowPrinter2 {
    list: VecDeque<i32>,
}
impl SlowPrinter2 {
    pub fn print(&mut self) -> impl Future<Output = ()> + '_ {
        poll_fn(move |_| {
            if let Some(x) = self.list.pop_front() {
                println!("{}", x);
                Poll::Pending
            } else {
                Poll::Ready(())
            }
        })
    }
}

async fn print_some2(mut printer: SlowPrinter2) {
    printer.print().await;
    printer.print().await;
}
```

**Comment by Finomnis** [comment]
I know this is old, but let me answer you anyway.

A future can only be awaited once, because a future produces a value. It cannot produce a value twice; a future always produces exactly one value. Hence calling `await` on it consumes it. And once consumed, you cannot call it again.

You can call `printer.print().await` many times because `print()` here **produces** a future. So every future still produces exactly one value, but you now have two futures.

Does that answer your question?

**Comment by Finomnis** [comment]
And while unrelated, be very careful with using `Pending` like this. It works with `cassette`, but if used with any other executer, it will deadlock. A `cx.waker().wake_by_ref();` is required when `Pending` to notify the executor that we should be polled again.

**Comment by Finomnis** [comment]
I'll close this in a week or so unless you have additional questions.

**Comment by Slamy** [comment]
Wow, this is like a long time ago. I've actually managed to use this crate in the meantime. I've written a floppy disk writing firmware for a STM32 (https://github.com/Slamy/STM32-USBFloppyTracer/tree/main) and some components use Cassette to bring some beauty into the state machines. I do realize that I maybe should have done it differently. There are now tools like embassy or rtic but ... it was my first embedded Rust project. I wanted to understand what was going on and Cassette brought Embedded Async to the minimum and there was no obfuscation on what happened.
So, thank you. I'm closing this now as my understanding of Rust is now much bigger. The learning curve of this language was a problem at first.
